### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by mohitCodepy** [ervikassingh/nft-market#2]
![image](https://user-images.githubusercontent.com/61349019/133423106-d46145d2-3ab3-45ee-9b48-93dae164ad5c.png)

./src/components/explore/explore.js
Module not found: Can't resolve '../../abis/ImageContract.json' in 'C:\Users\HP\Desktop\NFT\nft-market\src\components\explore'

**Comment by ervikassingh** [comment]
The abis are not yet created, you have to migrate your code to the blockchain. Also remember to add your private key to truffle.config file. Then run the following command :
truffle migrate --reset
